services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: paypal_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-paypal_app}
      POSTGRES_USER: ${DB_USERNAME:-paypal_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - paypal_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-paypal_user}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Laravel Backend
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: paypal_backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - ./backend/vendor:/var/www/vendor
    ports:
      - "8001:8000"
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE:-paypal_app}
      DB_USERNAME: ${DB_USERNAME:-paypal_user}
      DB_PASSWORD: ${DB_PASSWORD:-secret}
      APP_ENV: ${APP_ENV:-local}
      APP_DEBUG: ${APP_DEBUG:-true}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - paypal_network
    command: >
      sh -c "composer install &&
             php artisan key:generate --force &&
             php artisan config:clear &&
             php artisan migrate --force &&
             php artisan serve --host=0.0.0.0 --port=8000"

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: paypal_frontend
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    environment:
      - VITE_API_URL=http://localhost:8001
    depends_on:
      - app
    networks:
      - paypal_network
    command: npm run dev -- --host

networks:
  paypal_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
